version: "3.8"
services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - VITE_CLAUDE_API_KEY=${VITE_CLAUDE_API_KEY}
    env_file:
      - .env
    command: node server.js

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - NODE_ENV=development
    depends_on:
      - backend 